### ISSUE TITLE
Timeout issue....

### ISSUE THREAD

**Issue by zagnuts** [nonspecialist/pyraven#7]
Thought I'd give this a shot, and although I can happily see the data from the raven card when using minicom eg:
`minicom -D /dev/serial/by-id/usb-Rainforest_RFA-Z106-RA-PC_RAVEn_v2.3.21-if00-port0`
or
`minicom -D /dev/ttyUSB0`

when I try the raven script eg
`raven -p /dev/ttyUSB0` or just `raven`
I get a timeout message....

`Traceback (most recent call last):
  File "/usr/local/bin/raven", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/raven/__init__.py", line 55, in main
    print(json.dumps(raven_usb.get_connection_status()))
  File "/usr/local/lib/python2.7/dist-packages/raven/raven.py", line 122, in get_connection_status
    raise Exception("get_connection_status timeout")
Exception: get_connection_status timeout`

I get the same issue if I run it via sudo so I know it's not permissions related, and I know that the card itself is working as minicom displays the data just fine. I know it's been a while since this was created, and you may not see this message, just wondering (if you do see this) if you might have any ideas why this might be? The settings should be 8,N,1 but that's the default for pyserial so shouldn't need to be specified....

Doing a `python -m serial.tools.list_ports` gives 
`/dev/ttyAMA0        
/dev/ttyUSB0        
2 ports found` so python can see the ports

Just tried `python -m serial.tools.miniterm /dev/ttyUSB0 115200` and it showed the data coming through.... It's quite possible it's something dumb with my install so I'll keep looking for now and if I workout what the issue for me is I'll update this. :-)

**Comment by zagnuts** [comment]
Just tried this on a second Raspberry pi, and replicated the issue, dang it. ;-)
